name: Maven Package and Docker Build

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'feature/**'

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout Github repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Create secrets.yml
      run: |
        echo "token:placeholder" > secrets.yml

    - name: Execute package phase of default lifecycle
      run: mvn -X -B package

    - name: Execute maven help:evaluate to get jar name
      run: jarName=$(mvn help:evaluate -Dexpression=project.build.finalName -DforceStdout -q | sed 's/\[INFO\] \[stdout\] //').jar && echo "jarName:"$jarName

    - name: Execute maven help:evaluate to get name
      run: name=$(mvn help:evaluate -Dexpression=project.artifactId -DforceStdout -q | sed 's/\[INFO\] \[stdout\] //') && echo "name:"$name

    - name: Execute maven help:evaluate to get version
      run: version=$(mvn help:evaluate -Dexpression=project.version -DforceStdout -q | sed 's/\[INFO\] \[stdout\] //') && echo "version:"$version

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag $name:$version --build-arg JAR_NAME=$jarName

    - name: Tag the docker image with latest
      run: docker tag $name:$version $name:latest

    - name: Login to Github Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGE_PAT_CLASSIC }}

    - name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: $name:latest
        load: true
        provenance: false