name: Maven Package and Docker Build

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'feature/**'

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout Github repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Create secrets.yml
      run: |
        echo "token:placeholder" > secrets.yml

    - name: Execute package phase of default lifecycle
      run: mvn -X -B package

    - name: Variable assignment from mvn help:evaluate
      run: |
        echo "JAR_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -DforceStdout -q | sed 's/\[INFO\] \[stdout\] //').jar" >> "$GITHUB_ENV"
        echo "NAME=$(mvn help:evaluate -Dexpression=project.artifactId -DforceStdout -q | sed 's/\[INFO\] \[stdout\] //')" >> "$GITHUB_ENV"
        echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -DforceStdout -q | sed 's/\[INFO\] \[stdout\] //')" >> "$GITHUB_ENV"

    - name: Build the docker image
      run: docker build . --file Dockerfile --tag $NAME:$VERSION --build-arg JAR_NAME=$JAR_NAME

    - name: Tag the docker image with latest
      run: docker tag $NAME:$VERSION $NAME:latest

    - name: Login to Github Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PACKAGE_PAT_CLASSIC }}

    - name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.NAME }}:latest
        load: true
        provenance: false