# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches:
    - 'main'
    - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout Github repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: print present working directory
      run: echo $PWD

    - name: print contents of directory
      run: ls -lt

    - name: print default settings.xml
      run: cat settings.xml

    - name: Execute package phase of default lifecycle
      run: mvn -X -B package -s settings.xml

    - name: print present working directory 2
      run: echo $PWD

    - name: print contents of directory 2
      run: ls -lt

    - name: print contents of target directory
      run: ls target -lt

    - name: echo actor
      run: echo ${{ github.actor }}

    - name: echo token
      run: echo ${{ github.token }}

    - name: print present working directory 2
      run: echo $PWD

    - name: print contents of directory 2
      run: ls -lt

    - name: print alternate settings.xml
      run: cat ${{ github.workspace }}/settings.xml

    - name: Execute plugin goal deploy:deploy to publish to github packages
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_PAT_CLASSIC }}
      run: mvn -X jar:jar deploy:deploy -s ${{github.workspace}}/settings.xml

